// const Products = [
//     {
//         id: 'PROD001',
//         name: 'Iwak Bandeng',
//         description: 'Ikan bandeng segar berkualitas tinggi.',
//         media: 'https://example.com/images/iwak-bandeng.jpg',
//         price: 200000,
//         discount: 10000,
//         stok: 10,
//         type: 'Ikan Segar',
//         category: 'Makanan Laut',
//         weight: 1.2,
//         height: 10,
//         length: 30,
//         width: 10,
//         isPublished: true,
//     },
//     {
//         id: 'PROD002',
//         name: 'Iwak Lele',
//         description: 'Ikan lele segar dari peternakan terbaik.',
//         media: 'https://example.com/images/iwak-lele.jpg',
//         price: 300000,
//         discount: 15000,
//         stok: 90,
//         type: 'Ikan Segar',
//         category: 'Makanan Laut',
//         weight: 0.8,
//         height: 8,
//         length: 25,
//         width: 8,
//         isPublished: true,
        
//     },
//     {
//         id: 'PROD003',
//         name: 'Iwak Peyek',
//         description: 'Peyek ikan renyah dengan bumbu khas.',
//         media: 'https://example.com/images/iwak-peyek.jpg',
//         price: 400000,
//         discount: 20000,
//         stok: 5,
//         type: 'Camilan',
//         category: 'Makanan Ringan',
//         weight: 0.5,
//         height: 5,
//         length: 20,
//         width: 15,
//         isPublished: true,
//     },
//     {
//         id: 'PROD004',
//         name: 'Iwak Gurame',
//         description: 'Ikan gurame segar berkualitas tinggi.',
//         media: 'https://example.com/images/iwak-gurame.jpg',
//         price: 400000,
//         discount: 10000,
//         stok: 90,
//         type: 'Ikan Segar',
//         category: 'Makanan Laut',
//         weight: 1.2,
//         height: 10,
//         length: 30,
//         width: 10,
//         isPublished: true,
//     },
//     {
//         id: 'PROD005',
//         name: 'Iwak Nila',
//         description: 'Ikan nila segar berkualitas tinggi.',
//         media: 'https://example.com/images/iwak-nila.jpg',
//         price: 300000,
//         discount: 10000,
//         stok: 0,
//         type: 'Ikan Segar',
//         category: 'Makanan Laut',
//         weight: 1.2,
//         height: 10,
//         length: 30,
//         width: 10,
//         isPublished: true,
//     },
//     {
//         id: 'PROD006',
//         name: 'Iwak Mujair',
//         description: 'Ikan mujair segar berkualitas tinggi.',
//         media: 'https://example.com/images/iwak-mujair.jpg',
//         price: 200000,
//         discount: 10000,
//         stok: 10,
//         type: 'Ikan Segar',
//         category: 'Makanan Laut',
//         weight: 1.2,
//         height: 10,
//         length: 30,
//         width: 10,
//         isPublished: false,
//     },
// ];

// export default Products;


const Products = [
    {
        id: 'PROD001',
        name: 'Iwak Bandeng',
        description: 'Ikan bandeng segar berkualitas tinggi.',
        media: 'https://example.com/images/iwak-bandeng.jpg',
        price: 200000,
        discount: 10000,
        stok: 10,
        type: {
            warna: ['Putih', 'Silver'],
            ukuran: ['S', 'M', 'L'],
            jenis_ikan: ['Bandeng'],
        },
        category: 'Makanan Laut',
        weight: 1.2,
        dimensions: { height: 10, length: 30, width: 10 },
        isPublished: true,
    },
    {
        id: 'PROD002',
        name: 'Iwak Lele',
        description: 'Ikan lele segar dari peternakan terbaik.',
        media: 'https://example.com/images/iwak-lele.jpg',
        price: 300000,
        discount: 15000,
        stok: 90,
        type: {
            warna: ['Hitam', 'Abu-abu'],
            ukuran: ['S', 'M', 'L'],
            jenis_ikan: ['Lele'],
        },
        category: 'Makanan Laut',
        weight: 0.8,
        dimensions: { height: 8, length: 25, width: 8 },
        isPublished: true,
    },
    {
        id: 'PROD003',
        name: 'Iwak Peyek',
        description: 'Peyek ikan renyah dengan bumbu khas.',
        media: 'https://example.com/images/iwak-peyek.jpg',
        price: 400000,
        discount: 20000,
        stok: 5,
        type: {
            warna: ['Kuning Coklat'],
            ukuran: ['Small Pack', 'Medium Pack', 'Large Pack'],
            jenis_ikan: ['Peyek'],
        },
        category: 'Makanan Ringan',
        weight: 0.5,
        dimensions: { height: 5, length: 20, width: 15 },
        isPublished: true,
    },
    {
        id: 'PROD004',
        name: 'Iwak Gurame',
        description: 'Ikan gurame segar berkualitas tinggi.',
        media: 'https://example.com/images/iwak-gurame.jpg',
        price: 400000,
        discount: 10000,
        stok: 90,
        type: {
            warna: ['Merah', 'Putih'],
            ukuran: ['S', 'M', 'L'],
            jenis_ikan: ['Gurame Sisik Hitam'],
        },
        category: 'Makanan Laut',
        weight: 1.2,
        dimensions: { height: 10, length: 30, width: 10 },
        isPublished: true,
    },
    {
        id: 'PROD005',
        name: 'Iwak Nila',
        description: 'Ikan nila segar berkualitas tinggi.',
        media: 'https://example.com/images/iwak-nila.jpg',
        price: 300000,
        discount: 10000,
        stok: 0,
        type: {
            warna: ['Merah', 'Hitam'],
            ukuran: ['S', 'M', 'L'],
            jenis_ikan: ['Nila Sirip Putih', 'Nila Sirip Pink'],
        },
        category: 'Makanan Laut',
        weight: 1.2,
        dimensions: { height: 10, length: 30, width: 10 },
        isPublished: true,
    },
    {
        id: 'PROD006',
        name: 'Iwak Mujair',
        description: 'Ikan mujair segar berkualitas tinggi.',
        media: 'https://example.com/images/iwak-mujair.jpg',
        price: 200000,
        discount: 10000,
        stok: 10,
        type: {
            warna: ['Abu-abu', 'Coklat'],
            ukuran: ['S', 'M', 'L'],
            jenis_ikan: ['Mujair'],
        },
        category: 'Makanan Laut',
        weight: 1.2,
        dimensions: { height: 10, length: 30, width: 10 },
        isPublished: false,
    },
];

export default Products;
